version: '3.2'

services:
  # https://hub.docker.com/r/confluentinc/cp-zookeeper/
  zookeeper:
    image: confluentinc/cp-zookeeper:5.1.2
    container_name: zookeeper
    hostname: zookeeper
    env_file:
      - ../.env
    ports:
      - $ZOOKEPER__PORT:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: $ZOOKEPER__PORT
      TZ: $TZ

  # https://hub.docker.com/r/confluentinc/cp-kafka/
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:5.1.2
    hostname: kafka
    env_file:
      - ../.env
    ports:
      - $KAFKA__PORT:9092
    environment:
      KAFKA_LISTENERS: PLAINTEXT://kafka:19092,LISTENER_DOCKER_EXTERNAL://kafka:$KAFKA__PORT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-kafka}:$KAFKA__PORT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:$ZOOKEPER__PORT"
      KAFKA_BROKER_ID: 1
      KAFKA_NUM_PARTITIONS: $KAFKA__NUM_PARTITIONS
      KAFKA_DEFAULT_REPLICATION_FACTOR: $KAFKA__NUM_REPLICAS
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
    restart: always
    volumes:
      # directory for logs
      - $KAFKA__DATA:/var/lib/kafka/data
      # directory of configs
      - $KAFKA__CONFIGS:/etc/kafka
    depends_on:
      - zookeeper
    command: >
          sh -c "((sleep 15 && \
                /usr/bin/kafka-topics \
                --zookeeper $DOCKER_HOST_IP:$ZOOKEPER__PORT \
                --create --topic $KAFKA__TOPIC \
                --partitions $KAFKA__NUM_PARTITIONS \
                --replication-factor $KAFKA__NUM_REPLICAS)&) && \
                /etc/confluent/docker/run "